name: Daily Stock Data Fetcher (Step 1)

# 設定排程：每天 UTC 時間 9 點執行 (大約是台灣時間下午 5 點)。
# 這是在市場收盤後，適合抓取日線資料的時間點。
on:
  schedule:
    - cron: '0 9 * * *'
  # 允許手動觸發 (方便測試)
  workflow_dispatch:

jobs:
  fetch_and_commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4
        # 這是關鍵！使用 GITHUB_TOKEN 來讓 action 具備 commit 權限
        with:
          fetch-depth: 0 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 3. Install Dependencies
        run: pip install -r stockData_retrieve/requirements.txt

      - name: 4. Execute Python Script (Fetch Data)
        # 執行您的資料擷取腳本，它會更新 stock_data.db 檔案
        run: python stockData_retrieve/stock_fetcher.py

      - name: 5. Auto Commit Updated DB File
        # 使用專門的 Action 來提交檔案變更
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: 自動更新股價資料 (GitHub Actions)"
          # 只提交變動過的 .db 檔案
          file_pattern: 'stockData/stock_data_*.db'  
          # 使用預設 GITHUB_TOKEN 進行認證
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'