name: Daily Stock Data Fetcher (Step 1)

# 設定排程：每天 UTC 時間 9 點執行 (大約是台灣時間下午 5 點)。
on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

# --- BEGIN MODIFICATION ---
permissions:
  contents: write # 賦予 GITHUB_TOKEN 寫入 (commit/push) 倉庫內容的權限
# --- END MODIFICATION ---

jobs:
  fetch_and_commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4
        with:
          # 確保有完整讀寫權限
          fetch-depth: 0 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 3. Install Dependencies
        # 使用 stockData_retrieve/requirements.txt 安裝所有依賴 (包含 pytz, holidays)
        run: pip install -r stockData_retrieve/requirements.txt

      - name: 4. Execute Python Script (Fetch Data & Debug)
        run: |
          echo "Starting Python script execution..."
          # 執行 Python 腳本
          python stockData_retrieve/daily_stock_fetcher.py
          echo "--- File Status Check ---"
          # 偵錯：顯示資料夾內容，確認檔案是否生成
          ls -la stockData/

      - name: 5. Auto Commit Updated DB File
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: 自動新增股價資料 DB 檔案 (GitHub Actions)"
          # 使用萬用字元 (*) 來匹配每天新增的檔案
          file_pattern: 'stockData/stock_data_*.db' 
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
